services:
  - type: web
    name: multimodal-emotion-backend
    runtime: python
    plan: starter
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 180
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: USE_GPU
        value: "false"
      - key: REACT_APP_VERCEL_URL
        sync: false
